import "./globals.css";
import SideBar from "./components/Sidebar";
import RightPanel from "./components/RightPanel";
import ClientOnly from "./components/ClientOnly";

export const metadata = {
  title: "X Clone App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className='min-h-screen transition-colors' data-theme="light" 
      >
        <div className="flex h-screen">
          <aside className="hidden md:flex md:w-1/6 lg:w-1/6 w-fit border-gray-100 p-5 justify-end">
            <SideBar></SideBar>
          </aside>
          <main className="flex-1 flex  flex-col overflow-y-auto">
            {children}
          </main>
          <ClientOnly>
            <aside className="hidden lg:flex lg:w-1/4 border-gray-100 p-4">
              <RightPanel />
            </aside>
          </ClientOnly>
        </div>
      </body>
    </html>
  );
}
