import "./globals.css";
import SideBar from "./components/Sidebar";

export const metadata = {
  title: "X Clone App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className='bg-black  text-white min-h-screen' 
      >
        <div className="flex h-screen">
          <aside className="w-fit border-r border-gray-100 p-4">
            <SideBar></SideBar>
          </aside>
          <main className="flex-1 flex  flex-col overflow-y-auto">
            {children}
          </main>
          <aside className="w-1/4 border-l border-gray-100 p-4">
            <p>Right Pannel</p>
          </aside>
        </div>
      </body>
    </html>
  );
}
